-- -----------------------------------------------------------------------------------------------
INSERT INTO
    LiveBirthRegistrations (
        child_name,
        child_sex,
        child_dob,
        child_place_of_birth,
        child_birth_plurality,
        child_weight_at_birth,
        child_aid_rendered,
        mother_name,
        mother_dob,
        mother_place_of_birth,
        mother_residence,
        mother_phone,
        mother_marital_status,
        mother_citizenship,
        father_name,
        father_dob,
        father_place_of_birth,
        father_residence,
        father_phone,
        father_marital_status,
        father_citizenship,
        declarant_name,
        declarant_relation_to_child,
        declarant_sex,
        declarant_dob,
        declarant_place_of_birth,
        declarant_residence,
        declarant_phone,
        rgstrnt_user
    )
VALUES
    (
        'Emma Johnson',
        'F',
        '2023-05-15',
        'New York',
        1,
        3.2,
        NULL,
        'Alice Johnson',
        '1990-04-10',
        'Chicago',
        '123 Main St, New York, NY 10001',
        '5551234567',
        'married',
        'USA',
        'John Johnson',
        '1988-03-20',
        'Los Angeles',
        '123 Main St, New York, NY 10001',
        '5557894560',
        'married',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1
    ),
    (
        'Noah Smith',
        'M',
        '2023-06-20',
        'Los Angeles',
        1,
        3.5,
        'Medical assistance provided',
        'Sophia Smith',
        '1992-07-25',
        'San Francisco',
        '987 Elm St, Los Angeles, CA 90001',
        '9876543210',
        'married',
        'USA',
        'Michael Smith',
        '1990-06-15',
        'San Diego',
        '987 Elm St, Los Angeles, CA 90001',
        '9873216540',
        'married',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2
    ),
    (
        'Olivia Williams',
        'F',
        '2023-07-10',
        'Houston',
        1,
        3.0,
        NULL,
        'Emily Williams',
        '1995-01-12',
        'Dallas',
        '567 Oak Rd, Houston, TX 77001',
        '5678901234',
        'single',
        'USA',
        'Daniel Brown',
        '1993-02-18',
        'Austin',
        '567 Oak Rd, Houston, TX 77001',
        '5671238901',
        'single',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        3
    ),
    (
        'Liam Davis',
        'M',
        '2023-08-05',
        'Miami',
        1,
        3.8,
        NULL,
        'Isabella Davis',
        '1985-09-08',
        'Orlando',
        '111 Palm Ave, Miami, FL 33001',
        '1112223333',
        'widowed',
        'USA',
        'Jacob Davis',
        '1980-04-22',
        'Tampa',
        '111 Palm Ave, Miami, FL 33001',
        '1112223334',
        'widowed',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        4
    );
INSERT INTO
    LiveBirthRegistrations (
        child_name,
        child_sex,
        child_dob,
        child_place_of_birth,
        child_birth_plurality,
        child_weight_at_birth,
        child_aid_rendered,
        mother_name,
        mother_dob,
        mother_place_of_birth,
        mother_residence,
        mother_phone,
        mother_marital_status,
        mother_citizenship,
        father_name,
        father_dob,
        father_place_of_birth,
        father_residence,
        father_phone,
        father_marital_status,
        father_citizenship,
        declarant_name,
        declarant_relation_to_child,
        declarant_sex,
        declarant_dob,
        declarant_place_of_birth,
        declarant_residence,
        declarant_phone,
        rgstrnt_user
    )
VALUES
    (
        'Sophia Olivia',
        'F',
        '2024-03-15',
        'New York City, NY',
        1,
        7.2,
        'Apgar score 9/10, no complications',
        'Emily Johnson',
        '1990-07-22',
        'Los Angeles, CA',
        '123 Main St, New York, NY 10001',
        '555-1234',
        'married',
        'United States',
        'Michael Johnson',
        '1988-11-05',
        'Chicago, IL',
        '123 Main St, New York, NY 10001',
        '555-5678',
        'married',
        'United States',
        'Sarah Williams',
        'Grandmother',
        'F',
        '1960-02-14',
        'Boston, MA',
        '456 Oak Rd, New York, NY 10002',
        '555-9012',
        1
    ),
    (
        'Ethan Alexander',
        'M',
        '2024-05-01',
        'San Francisco, CA',
        1,
        8.1,
        'Apgar score 10/10, no complications',
        'Olivia Davis',
        '1992-04-30',
        'Seattle, WA',
        '789 Elm St, San Francisco, CA 94101',
        '555-3456',
        'single',
        'United States',
        'Jacob Davis',
        '1990-09-15',
        'Portland, OR',
        '789 Elm St, San Francisco, CA 94101',
        '555-7890',
        'single',
        'United States',
        'David Lee',
        'Uncle',
        'M',
        '1985-06-20',
        'San Jose, CA',
        '159 Oak Ave, San Francisco, CA 94102',
        '555-2468',
        2
    ),
    (
        'Isabella Grace',
        'F',
        '2024-01-20',
        'Chicago, IL',
        1,
        6.8,
        'Apgar score 8/10, minor respiratory distress',
        'Sophia Hernandez',
        '1988-12-03',
        'Mexico City, Mexico',
        '321 Maple Rd, Chicago, IL 60601',
        '555-7890',
        'married',
        'Mexico',
        'Miguel Hernandez',
        '1985-05-12',
        'Guadalajara, Mexico',
        '321 Maple Rd, Chicago, IL 60601',
        '555-4321',
        'married',
        'Mexico',
        'Maria Gonzalez',
        'Aunt',
        'F',
        '1975-09-08',
        'Tijuana, Mexico',
        '654 Oak St, Chicago, IL 60602',
        '555-8765',
        3
    );

INSERT INTO
    LiveBirthRegistrations (
        child_name,
        child_sex,
        child_dob,
        child_place_of_birth,
        child_birth_plurality,
        child_weight_at_birth,
        child_aid_rendered,
        mother_name,
        mother_dob,
        mother_place_of_birth,
        mother_residence,
        mother_phone,
        mother_marital_status,
        mother_citizenship,
        father_name,
        father_dob,
        father_place_of_birth,
        father_residence,
        father_phone,
        father_marital_status,
        father_citizenship,
        declarant_name,
        declarant_relation_to_child,
        declarant_sex,
        declarant_dob,
        declarant_place_of_birth,
        declarant_residence,
        declarant_phone,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'Emily Johnson',
        'F',
        '2023-01-05',
        'New York',
        1,
        3.2,
        NULL,
        'Jane Johnson',
        '1995-08-12',
        'Chicago',
        'New York',
        '555-555-5555',
        'married',
        'USA',
        'John Johnson',
        '1990-06-01',
        'Los Angeles',
        'Chicago',
        '666-666-6666',
        'married',
        'USA',
        'Jane Johnson',
        'Mother',
        'F',
        '1995-08-12',
        'Chicago',
        'New York',
        '555-555-5555',
        '2023-01-05 09:00:00',
        1
    );

INSERT INTO
    `livebirthregistrations` (
        `child_name`,
        `child_sex`,
        `child_dob`,
        `child_place_of_birth`,
        `child_birth_plurality`,
        `child_weight_at_birth`,
        `child_aid_rendered`,
        `mother_name`,
        `mother_dob`,
        `mother_place_of_birth`,
        `mother_residence`,
        `mother_phone`,
        `mother_marital_status`,
        `mother_citizenship`,
        `father_name`,
        `father_dob`,
        `father_place_of_birth`,
        `father_residence`,
        `father_phone`,
        `father_marital_status`,
        `father_citizenship`,
        `declarant_name`,
        `declarant_relation_to_child`,
        `declarant_sex`,
        `declarant_dob`,
        `declarant_place_of_birth`,
        `declarant_residence`,
        `declarant_phone`,
        `registration_date`,
        `rgstrnt_user`
    )
VALUES
    (
        'Emily Johnson', -- child_name
        'F', -- child_sex
        '2023-05-12', -- child_dob
        'New York', -- child_place_of_birth
        1, -- child_birth_plurality
        '3.5', -- child_weight_at_birth (in kg)
        'None', -- child_aid_rendered
        'Jane Johnson', -- mother_name
        '1995-08-15', -- mother_dob
        'Chicago', -- mother_place_of_birth
        'New York', -- mother_residence
        '555-555-5555', -- mother_phone
        'married', -- mother_marital_status
        'USA', -- mother_citizenship
        'John Johnson', -- father_name
        '1990-06-01', -- father_dob
        'Los Angeles', -- father_place_of_birth
        'Chicago', -- father_residence
        '666-666-6666', -- father_phone
        'married', -- father_marital_status
        'USA', -- father_citizenship
        'Jane Johnson', -- declarant_name
        'Mother', -- declarant_relation_to_child
        'F', -- declarant_sex
        '1995-08-15', -- declarant_dob
        'Chicago', -- declarant_place_of_birth
        'New York', -- declarant_residence
        '555-555-5555', -- declarant_phone
        '2023-05-12 09:00:00', -- registration_date
        1 -- rgstrnt_user
    ),
    (
        'Michael Smith', -- child_name
        'M', -- child_sex
        '2023-06-25', -- child_dob
        'Los Angeles', -- child_place_of_birth
        1, -- child_birth_plurality
        '3.2', -- child_weight_at_birth (in kg)
        'Vaccination', -- child_aid_rendered
        'Emily Smith', -- mother_name
        '1990-01-01', -- mother_dob
        'New York', -- mother_place_of_birth
        'Los Angeles', -- mother_residence
        '111-111-1111', -- mother_phone
        'single', -- mother_marital_status
        'USA', -- mother_citizenship
        'John Smith', -- father_name
        '1985-06-15', -- father_dob
        'Los Angeles', -- father_place_of_birth
        'New York', -- father_residence
        '222-222-2222', -- father_phone
        'married', -- father_marital_status
        'USA', -- father_citizenship
        'Emily Smith', -- declarant_name
        'Mother', -- declarant_relation_to_child
        'F', -- declarant_sex
        '1990-01-01', -- declarant_dob
        'New York', -- declarant_place_of_birth
        'Los Angeles', -- declarant_residence
        '111-111-1111', -- declarant_phone
        '2023-06-25 10:30:00', -- registration_date
        2 -- rgstrnt_user
    );

INSERT INTO
    `livebirthregistrations` (
        `child_name`,
        `child_sex`,
        `child_dob`,
        `child_place_of_birth`,
        `child_birth_plurality`,
        `child_weight_at_birth`,
        `child_aid_rendered`,
        `mother_name`,
        `mother_dob`,
        `mother_place_of_birth`,
        `mother_residence`,
        `mother_phone`,
        `mother_marital_status`,
        `mother_citizenship`,
        `father_name`,
        `father_dob`,
        `father_place_of_birth`,
        `father_residence`,
        `father_phone`,
        `father_marital_status`,
        `father_citizenship`,
        `declarant_name`,
        `declarant_relation_to_child`,
        `declarant_sex`,
        `declarant_dob`,
        `declarant_place_of_birth`,
        `declarant_residence`,
        `declarant_phone`,
        `registration_date`,
        `rgstrnt_user`
    )
VALUES
    (
        'Emily Johnson', -- child_name
        'F', -- child_sex
        '2023-05-12', -- child_dob
        'New York', -- child_place_of_birth
        1, -- child_birth_plurality
        '3.5', -- child_weight_at_birth (in kg)
        'None', -- child_aid_rendered
        'Jane Johnson', -- mother_name
        '1995-08-15', -- mother_dob
        'Chicago', -- mother_place_of_birth
        'New York', -- mother_residence
        '555-555-5555', -- mother_phone
        'married', -- mother_marital_status
        'USA', -- mother_citizenship
        'John Johnson', -- father_name
        '1990-06-01', -- father_dob
        'Los Angeles', -- father_place_of_birth
        'Chicago', -- father_residence
        '666-666-6666', -- father_phone
        'married', -- father_marital_status
        'USA', -- father_citizenship
        'Jane Johnson', -- declarant_name
        'Mother', -- declarant_relation_to_child
        'F', -- declarant_sex
        '1995-08-15', -- declarant_dob
        'Chicago', -- declarant_place_of_birth
        'New York', -- declarant_residence
        '555-555-5555', -- declarant_phone
        '2023-05-12 09:00:00', -- registration_date
        1 -- rgstrnt_user
    ),
    (
        'Michael Smith', -- child_name
        'M', -- child_sex
        '2023-06-25', -- child_dob
        'Los Angeles', -- child_place_of_birth
        1, -- child_birth_plurality
        '3.2', -- child_weight_at_birth (in kg)
        'Vaccination', -- child_aid_rendered
        'Emily Smith', -- mother_name
        '1990-01-01', -- mother_dob
        'New York', -- mother_place_of_birth
        'Los Angeles', -- mother_residence
        '111-111-1111', -- mother_phone
        'single', -- mother_marital_status
        'USA', -- mother_citizenship
        'John Smith', -- father_name
        '1985-06-15', -- father_dob
        'Los Angeles', -- father_place_of_birth
        'New York', -- father_residence
        '222-222-2222', -- father_phone
        'married', -- father_marital_status
        'USA', -- father_citizenship
        'Emily Smith', -- declarant_name
        'Mother', -- declarant_relation_to_child
        'F', -- declarant_sex
        '1990-01-01', -- declarant_dob
        'New York', -- declarant_place_of_birth
        'Los Angeles', -- declarant_residence
        '111-111-1111', -- declarant_phone
        '2023-06-25 10:30:00', -- registration_date
        2 -- rgstrnt_user
    );

INSERT INTO
    LiveBirthRegistrations (
        child_name,
        child_sex,
        child_dob,
        child_place_of_birth,
        child_birth_plurality,
        child_weight_at_birth,
        child_aid_rendered,
        mother_name,
        mother_dob,
        mother_place_of_birth,
        mother_residence,
        mother_phone,
        mother_marital_status,
        mother_citizenship,
        father_name,
        father_dob,
        father_place_of_birth,
        father_residence,
        father_phone,
        father_marital_status,
        father_citizenship,
        declarant_name,
        declarant_relation_to_child,
        declarant_sex,
        declarant_dob,
        declarant_place_of_birth,
        declarant_residence,
        declarant_phone,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'Emily Johnson',
        'F',
        '2023-01-05',
        'New York',
        1,
        3.2,
        NULL,
        'Jane Johnson',
        '1995-08-12',
        'Chicago',
        'New York',
        '555-555-5555',
        'married',
        'USA',
        'John Johnson',
        '1990-06-01',
        'Los Angeles',
        'Chicago',
        '666-666-6666',
        'married',
        'USA',
        'Jane Johnson',
        'Mother',
        'F',
        '1995-08-12',
        'Chicago',
        'New York',
        '555-555-5555',
        '2023-01-05 09:00:00',
        1
    );

INSERT INTO
    LiveBirthRegistrations (
        child_name,
        child_sex,
        child_dob,
        child_place_of_birth,
        child_birth_plurality,
        child_weight_at_birth,
        child_aid_rendered,
        mother_name,
        mother_dob,
        mother_place_of_birth,
        mother_residence,
        mother_phone,
        mother_marital_status,
        mother_citizenship,
        father_name,
        father_dob,
        father_place_of_birth,
        father_residence,
        father_phone,
        father_marital_status,
        father_citizenship,
        declarant_name,
        declarant_relation_to_child,
        declarant_sex,
        declarant_dob,
        declarant_place_of_birth,
        declarant_residence,
        declarant_phone,
        rgstrnt_user
    )
VALUES
    (
        'Sophia Olivia',
        'F',
        '2024-03-15',
        'New York City, NY',
        1,
        7.2,
        'Apgar score 9/10, no complications',
        'Emily Johnson',
        '1990-07-22',
        'Los Angeles, CA',
        '123 Main St, New York, NY 10001',
        '555-1234',
        'married',
        'United States',
        'Michael Johnson',
        '1988-11-05',
        'Chicago, IL',
        '123 Main St, New York, NY 10001',
        '555-5678',
        'married',
        'United States',
        'Sarah Williams',
        'Grandmother',
        'F',
        '1960-02-14',
        'Boston, MA',
        '456 Oak Rd, New York, NY 10002',
        '555-9012',
        1
    ),
    (
        'Ethan Alexander',
        'M',
        '2024-05-01',
        'San Francisco, CA',
        1,
        8.1,
        'Apgar score 10/10, no complications',
        'Olivia Davis',
        '1992-04-30',
        'Seattle, WA',
        '789 Elm St, San Francisco, CA 94101',
        '555-3456',
        'single',
        'United States',
        'Jacob Davis',
        '1990-09-15',
        'Portland, OR',
        '789 Elm St, San Francisco, CA 94101',
        '555-7890',
        'single',
        'United States',
        'David Lee',
        'Uncle',
        'M',
        '1985-06-20',
        'San Jose, CA',
        '159 Oak Ave, San Francisco, CA 94102',
        '555-2468',
        2
    ),
    (
        'Isabella Grace',
        'F',
        '2024-01-20',
        'Chicago, IL',
        1,
        6.8,
        'Apgar score 8/10, minor respiratory distress',
        'Sophia Hernandez',
        '1988-12-03',
        'Mexico City, Mexico',
        '321 Maple Rd, Chicago, IL 60601',
        '555-7890',
        'married',
        'Mexico',
        'Miguel Hernandez',
        '1985-05-12',
        'Guadalajara, Mexico',
        '321 Maple Rd, Chicago, IL 60601',
        '555-4321',
        'married',
        'Mexico',
        'Maria Gonzalez',
        'Aunt',
        'F',
        '1975-09-08',
        'Tijuana, Mexico',
        '654 Oak St, Chicago, IL 60602',
        '555-8765',
        3
    );

-- -----------------------------------------------------------------------------------------------
INSERT INTO
    LiveBirthRegistrations (
        child_name,
        child_sex,
        child_dob,
        child_place_of_birth,
        child_birth_plurality,
        child_weight_at_birth,
        child_aid_rendered,
        mother_name,
        mother_dob,
        mother_place_of_birth,
        mother_residence,
        mother_phone,
        mother_marital_status,
        mother_citizenship,
        father_name,
        father_dob,
        father_place_of_birth,
        father_residence,
        father_phone,
        father_marital_status,
        father_citizenship,
        declarant_name,
        declarant_relation_to_child,
        declarant_sex,
        declarant_dob,
        declarant_place_of_birth,
        declarant_residence,
        declarant_phone,
        rgstrnt_user
    )
VALUES
    (
        'Emma Johnson',
        'F',
        '2023-05-15',
        'New York',
        1,
        3.2,
        NULL,
        'Alice Johnson',
        '1990-04-10',
        'Chicago',
        '123 Main St, New York, NY 10001',
        '5551234567',
        'married',
        'USA',
        'John Johnson',
        '1988-03-20',
        'Los Angeles',
        '123 Main St, New York, NY 10001',
        '5557894560',
        'married',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1
    ),
    (
        'Noah Smith',
        'M',
        '2023-06-20',
        'Los Angeles',
        1,
        3.5,
        'Medical assistance provided',
        'Sophia Smith',
        '1992-07-25',
        'San Francisco',
        '987 Elm St, Los Angeles, CA 90001',
        '9876543210',
        'married',
        'USA',
        'Michael Smith',
        '1990-06-15',
        'San Diego',
        '987 Elm St, Los Angeles, CA 90001',
        '9873216540',
        'married',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        2
    ),
    (
        'Olivia Williams',
        'F',
        '2023-07-10',
        'Houston',
        1,
        3.0,
        NULL,
        'Emily Williams',
        '1995-01-12',
        'Dallas',
        '567 Oak Rd, Houston, TX 77001',
        '5678901234',
        'single',
        'USA',
        'Daniel Brown',
        '1993-02-18',
        'Austin',
        '567 Oak Rd, Houston, TX 77001',
        '5671238901',
        'single',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        3
    ),
    (
        'Liam Davis',
        'M',
        '2023-08-05',
        'Miami',
        1,
        3.8,
        NULL,
        'Isabella Davis',
        '1985-09-08',
        'Orlando',
        '111 Palm Ave, Miami, FL 33001',
        '1112223333',
        'widowed',
        'USA',
        'Jacob Davis',
        '1980-04-22',
        'Tampa',
        '111 Palm Ave, Miami, FL 33001',
        '1112223334',
        'widowed',
        'USA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        4
    );

INSERT INTO
    StillbirthRegistrations (
        child_full_name,
        child_sex,
        child_gestational_age_wks,
        mother_full_name,
        mother_dob,
        mother_marital_status,
        mother_residence,
        mother_citizenship,
        mother_phone,
        father_full_name,
        father_dob,
        father_marital_status,
        father_residence,
        father_citizenship,
        father_phone,
        delivery_date,
        delivery_place,
        pregnancy_plurality,
        pregnancy_duration,
        birth_order,
        fetal_death_conditions,
        fetal_death_explanation,
        reporter_full_name,
        reporter_sex,
        reporter_residence,
        reporter_phone,
        rgstrnt_user
    )
VALUES
    (
        'Emma Smith',
        'F',
        30,
        'Alice Smith',
        '1985-07-15',
        'married',
        '123 Main St, Anytown',
        'USA',
        '123-456-7890',
        'John Smith',
        '1980-03-20',
        'married',
        '123 Main St, Anytown',
        'USA',
        '123-456-7890',
        '2023-05-10',
        'General Hospital',
        1,
        36,
        1,
        'fetal_anomaly',
        'Severe fetal anomaly detected',
        'Dr. Sarah Brown',
        'F',
        '456 Oak Ave, Somecity',
        '987-654-3210',
        1
    ),
    (
        'James Johnson',
        'M',
        25,
        'Sarah Johnson',
        '1990-02-28',
        'married',
        '456 Elm St, Anothercity',
        'Canada',
        '987-654-3210',
        'Michael Johnson',
        '1988-11-10',
        'married',
        '456 Elm St, Anothercity',
        'Canada',
        '987-654-3210',
        '2023-08-20',
        'City Hospital',
        1,
        34,
        2,
        'maternal_conditions',
        'Maternal health complication',
        'Dr. David White',
        'M',
        '789 Pine Rd, Townsville',
        '234-567-8901',
        1
    ),
    (
        'Sophia Brown',
        'F',
        32,
        'Emily Brown',
        '1987-04-12',
        'single',
        '789 Maple Ave, Villageton',
        'UK',
        '234-567-8901',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2023-11-05',
        'Community Clinic',
        1,
        35,
        1,
        'placenta_complications',
        'Placental abruption',
        'Dr. Emma Green',
        'F',
        '901 Cedar Lane, Hamletville',
        '345-678-9012',
        2
    );

INSERT INTO
    StillbirthRegistrations (
        child_full_name,
        child_sex,
        child_gestational_age_wks,
        mother_full_name,
        mother_dob,
        mother_marital_status,
        mother_residence,
        mother_citizenship,
        mother_phone,
        father_full_name,
        father_dob,
        father_marital_status,
        father_residence,
        father_citizenship,
        father_phone,
        delivery_date,
        delivery_place,
        pregnancy_plurality,
        pregnancy_duration,
        birth_order,
        fetal_death_conditions,
        fetal_death_explanation,
        reporter_full_name,
        reporter_sex,
        reporter_residence,
        reporter_phone,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        'M',
        38,
        'Jane Doe',
        '1990-01-01',
        'married',
        'New York',
        'USA',
        '1234567890',
        'John Smith',
        '1985-06-15',
        'married',
        'Los Angeles',
        'USA',
        '1111111111',
        '2022-02-20',
        'Hospital',
        1,
        40,
        1,
        'maternal_conditions',
        'Preeclampsia',
        'Jane Doe',
        'F',
        'New York',
        '1234567890',
        '2022-02-20 14:30:00',
        1
    ),
    (
        'Emily Johnson',
        'F',
        32,
        'Michael Johnson',
        '1995-08-15',
        'married',
        'Chicago',
        'USA',
        '3333333333',
        'Michael Brown',
        '1990-03-01',
        'single',
        'Los Angeles',
        'USA',
        '4444444444',
        '2022-03-15',
        'Clinic',
        2,
        36,
        2,
        'placenta_complications',
        'Placental abruption',
        'Michael Johnson',
        'M',
        'Chicago',
        '3333333333',
        '2022-03-15 10:00:00',
        2
    ),
    (
        'Robert Brown',
        'M',
        40,
        'Sarah Brown',
        '1990-06-01',
        'married',
        'Los Angeles',
        'USA',
        '6666666666',
        'Robert Davis',
        '1980-01-01',
        'married',
        'New York',
        'USA',
        '7777777777',
        '2022-04-01',
        'Hospital',
        3,
        42,
        3,
        'fetal_anomaly',
        'Congenital heart defect',
        'Sarah Brown',
        'F',
        'Los Angeles',
        '6666666666',
        '2022-04-01 12:00:00',
        3
    );

INSERT INTO
    StillbirthRegistrations (
        child_full_name,
        child_sex,
        child_gestational_age_wks,
        mother_full_name,
        mother_dob,
        mother_marital_status,
        mother_residence,
        mother_citizenship,
        mother_phone,
        father_full_name,
        father_dob,
        father_marital_status,
        father_residence,
        father_citizenship,
        father_phone,
        delivery_date,
        delivery_place,
        pregnancy_plurality,
        pregnancy_duration,
        birth_order,
        fetal_death_conditions,
        fetal_death_explanation,
        reporter_full_name,
        reporter_sex,
        reporter_residence,
        reporter_phone,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        'M',
        38,
        'Jane Doe',
        '1990-01-01',
        'married',
        'New York',
        'USA',
        '1234567890',
        'John Smith',
        '1985-06-15',
        'married',
        'Los Angeles',
        'USA',
        '1111111111',
        '2022-02-20',
        'Hospital',
        1,
        40,
        1,
        'maternal_conditions',
        'Preeclampsia',
        'Jane Doe',
        'F',
        'New York',
        '1234567890',
        1
    ),
    (
        'Emily Johnson',
        'F',
        32,
        'Michael Johnson',
        '1995-08-15',
        'married',
        'Chicago',
        'USA',
        '3333333333',
        'Michael Brown',
        '1990-03-01',
        'single',
        'Los Angeles',
        'USA',
        '4444444444',
        '2022-03-15',
        'Clinic',
        2,
        36,
        2,
        'placenta_complications',
        'Placental abruption',
        'Michael Johnson',
        'M',
        'Chicago',
        '3333333333',
        2
    ),
    (
        'Robert Brown',
        'M',
        40,
        'Sarah Brown',
        '1990-06-01',
        'married',
        'Los Angeles',
        'USA',
        '6666666666',
        'Robert Davis',
        '1980-01-01',
        'married',
        'New York',
        'USA',
        '7777777777',
        '2022-04-01',
        'Hospital',
        3,
        42,
        3,
        'fetal_anomaly',
        'Congenital heart defect',
        'Sarah Brown',
        'F',
        'Los Angeles',
        '6666666666',
        3
    ),
    (
        'Sophia Garcia',
        'F',
        35,
        'Maria Garcia',
        '1992-06-30',
        'married',
        'Los Angeles',
        'USA',
        '9999999999',
        'Juan Garcia',
        '1990-03-15',
        'married',
        'Los Angeles',
        'USA',
        '1010101010',
        '2023-01-15',
        'Hospital',
        1,
        38,
        1,
        'fetal_infection',
        'Congenital cytomegalovirus infection',
        'Maria Garcia',
        'F',
        'Los Angeles',
        '9999999999',
        4
    ),
    (
        'Ethan Patel',
        'M',
        41,
        'Priya Patel',
        '1985-09-20',
        'married',
        'New York',
        'USA',
        '2020202020',
        'Raj Patel',
        '1980-12-01',
        'married',
        'New York',
        'USA',
        '3030303030',
        '2023-03-01',
        'Clinic',
        1,
        43,
        1,
        'other_obstetrical_complications',
        'Placental abruption',
        'Priya Patel',
        'F',
        'New York',
        '2020202020',
        5
    ),
    (
        'Isabella Hernandez',
        'F',
        38,
        'Alejandra Hernandez',
        '1988-11-10',
        'married',
        'Chicago',
        'USA',
        '4040404040',
        'Miguel Hernandez',
        '1985-05-01',
        'married',
        'Chicago',
        'USA',
        '5050505050',
        '2023-05-01',
        'Hospital',
        1,
        40,
        1,
        'fetal_anomaly',
        'Anencephaly',
        'Alejandra Hernandez',
        'F',
        'Chicago',
        '4040404040',
        6
    );

-- ------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO
    StillbirthRegistrations (
        child_full_name,
        child_sex,
        child_gestational_age_wks,
        mother_full_name,
        mother_dob,
        mother_marital_status,
        mother_residence,
        mother_citizenship,
        mother_phone,
        father_full_name,
        father_dob,
        father_marital_status,
        father_residence,
        father_citizenship,
        father_phone,
        delivery_date,
        delivery_place,
        pregnancy_plurality,
        pregnancy_duration,
        birth_order,
        fetal_death_conditions,
        fetal_death_explanation,
        reporter_full_name,
        reporter_sex,
        reporter_residence,
        reporter_phone,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'Emily Johnson',
        'F',
        30,
        'Jane Johnson',
        '1995-08-12',
        'married',
        'New York',
        'USA',
        '555-555-5555',
        'John Johnson',
        '1990-06-01',
        'married',
        'Chicago',
        'USA',
        '666-666-6666',
        '2023-01-05',
        'Hospital XYZ',
        1,
        40,
        1,
        'maternal_conditions',
        'Complications during pregnancy',
        'Dr. Sarah Brown',
        'F',
        'New York',
        '111-111-1111',
        '2023-01-05 11:00:00',
        1
    );

INSERT INTO
    MarriageRegistrations (
        spouse1_full_name,
        spouse1_sex,
        spouse1_dob,
        spouse1_place_of_birth,
        spouse1_citizenship,
        spouse1_previous_marital,
        spouse1_phone,
        spouse1_residence,
        spouse2_full_name,
        spouse2_sex,
        spouse2_dob,
        spouse2_place_of_birth,
        spouse2_citizenship,
        spouse2_previous_marital,
        spouse2_phone,
        spouse2_residence,
        witness1_full_name,
        witness1_sex,
        witness1_dob,
        witness1_citizenship,
        witness1_phone,
        witness1_residence,
        witness2_full_name,
        witness2_sex,
        witness2_dob,
        witness2_citizenship,
        witness2_phone,
        witness2_residence,
        marriage_date,
        marriage_place,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        'M',
        '1985-05-10',
        'New York',
        'USA',
        'single',
        '1234567890',
        'New York',
        'Jane Smith',
        'F',
        '1988-09-15',
        'Los Angeles',
        'USA',
        'single',
        '9876543210',
        'Los Angeles',
        'Michael Brown',
        'M',
        '1980-02-20',
        'Chicago',
        '1111111111',
        'Chicago',
        'Emily Davis',
        'F',
        '1983-07-25',
        'Houston',
        '2222222222',
        'Houston',
        '2022-05-20',
        'Church',
        1
    ),
    (
        'Robert Johnson',
        'M',
        '1990-03-15',
        'San Francisco',
        'USA',
        'divorced',
        '5555555555',
        'San Francisco',
        'Sarah Williams',
        'F',
        '1995-08-05',
        'Miami',
        'USA',
        'single',
        '6666666666',
        'Miami',
        'David Lee',
        'M',
        '1987-01-10',
        'Seattle',
        '3333333333',
        'Seattle',
        'Jessica Moore',
        'F',
        '1990-06-20',
        'Dallas',
        '4444444444',
        'Dallas',
        '2022-06-10',
        'Beach Resort',
        2
    ),
    (
        'William Turner',
        'M',
        '1982-11-30',
        'Boston',
        'USA',
        'widowed',
        '7777777777',
        'Boston',
        'Elizabeth Parker',
        'F',
        '1980-04-25',
        'Phoenix',
        'USA',
        'single',
        '8888888888',
        'Phoenix',
        'Daniel White',
        'M',
        '1985-09-12',
        'Denver',
        '9999999999',
        'Denver',
        'Sophia King',
        'F',
        '1988-12-15',
        'San Diego',
        '1010101010',
        'San Diego',
        '2022-07-15',
        'Vineyard',
        3
    );

-- ----------------
INSERT INTO
    MarriageRegistrations (
        spouse1_full_name,
        spouse1_sex,
        spouse1_dob,
        spouse1_place_of_birth,
        spouse1_citizenship,
        spouse1_previous_marital,
        spouse1_phone,
        spouse1_residence,
        spouse2_full_name,
        spouse2_sex,
        spouse2_dob,
        spouse2_place_of_birth,
        spouse2_citizenship,
        spouse2_previous_marital,
        spouse2_phone,
        spouse2_residence,
        witness1_full_name,
        witness1_sex,
        witness1_dob,
        witness1_citizenship,
        witness1_phone,
        witness1_residence,
        witness2_full_name,
        witness2_sex,
        witness2_dob,
        witness2_citizenship,
        witness2_phone,
        witness2_residence,
        marriage_date,
        marriage_place,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        'M',
        '1990-05-15',
        'New York',
        'USA',
        'single',
        '555-1234',
        'New York',
        'Jane Smith',
        'F',
        '1985-09-20',
        'Los Angeles',
        'USA',
        'single',
        '555-5678',
        'Los Angeles',
        'Michael Brown',
        'M',
        '1970-02-10',
        'Canada',
        '555-1111',
        'Toronto',
        'Emily Davis',
        'F',
        '1975-06-25',
        'USA',
        '555-2222',
        'New York',
        '2023-02-14',
        'New York City Hall',
        '2023-02-14 10:00:00',
        2
    );

INSERT INTO
    AdoptionRegistrations (
        adopter1_full_name,
        adopter1_dob,
        adopter1_sex,
        adopter1_birthplace,
        adopter1_citizenship,
        adopter1_phone,
        adopter1_residence,
        adopter1_occupation,
        adopter1_relationship_child,
        adopter1_relationship_adopter2,
        adopter1_relationship_chlds_parent,
        adopter2_full_name,
        adopter2_dob,
        adopter2_sex,
        adopter2_birthplace,
        adopter2_citizenship,
        adopter2_phone,
        adopter2_residence,
        adopter2_occupation,
        adopter2_relationship_child,
        adopter2_relationship_adopter1,
        adopter2_relationship_chlds_parent,
        category_of_adopters,
        child_full_name,
        child_dob,
        child_birthplace,
        child_sex,
        received_child_from,
        child_placer_address,
        child_placer_phone,
        adoption_date,
        adoption_type,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'Emily Johnson',
        '1988-04-10',
        'F',
        'New York',
        'USA',
        '555-1234',
        'New York',
        'Teacher',
        'Mother',
        NULL,
        NULL,
        'John Johnson',
        '1985-05-20',
        'M',
        'Los Angeles',
        'USA',
        '555-5678',
        'Los Angeles',
        'Engineer',
        'Father',
        NULL,
        NULL,
        'couple',
        'Michael Smith',
        '2010-12-25',
        'Los Angeles',
        'M',
        'Social Services',
        '123 Main St',
        '555-9999',
        '2021-01-15',
        'intercountry',
        '2021-01-15 10:00:00',
        2
    );

-- ---------------
INSERT INTO
    DeathRegistrations (
        deceased_full_name,
        deceased_title,
        deceased_sex,
        deceased_age,
        deceased_citizenship,
        death_date,
        death_place,
        death_cause,
        death_evidence_filepath,
        declarant_full_name,
        declarant_sex,
        declarant_phone,
        declarant_residence,
        declarant_relation,
        declarant_relation_other_text,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'John Smith',
        'Mr.',
        'M',
        75,
        'USA',
        '2023-03-15',
        'Los Angeles',
        'Heart attack',
        '/path/to/death_evidence.pdf',
        'Jane Smith',
        'F',
        '555-9999',
        'Los Angeles',
        'relative',
        NULL,
        '2023-03-15 15:30:00',
        2
    );

-- -------------------
INSERT INTO
    DivorceRegistrations (
        spouse1_full_name,
        spouse1_sex,
        spouse1_dob,
        spouse1_place_of_birth,
        spouse1_residence,
        spouse1_phone,
        spouse1_citizenship,
        spouse2_full_name,
        spouse2_sex,
        spouse2_dob,
        spouse2_place_of_birth,
        spouse2_residence,
        spouse2_phone,
        spouse2_citizenship,
        marriage_date,
        marriage_place,
        divorce_date,
        divorce_reference_filepath,
        divorce_reason,
        registration_date,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        'M',
        '1990-05-15',
        'New York',
        'New York',
        '555-1234',
        'USA',
        'Jane Doe',
        'F',
        '1992-03-20',
        'Los Angeles',
        'Los Angeles',
        '555-5678',
        'USA',
        '2015-07-10',
        'New York City Hall',
        '2021-04-30',
        '/path/to/divorce_reference.pdf',
        'Irreconcilable differences',
        '2021-05-01 09:00:00',
        1
    );

-- Inserting sample data into AdoptionRegistrations table
INSERT INTO
    AdoptionRegistrations (
        adopter1_full_name,
        adopter1_dob,
        adopter1_sex,
        adopter1_birthplace,
        adopter1_citizenship,
        adopter1_phone,
        adopter1_residence,
        adopter1_occupation,
        adopter1_relationship_child,
        adopter1_relationship_adopter2,
        adopter1_relationship_chlds_parent,
        adopter2_full_name,
        adopter2_dob,
        adopter2_sex,
        adopter2_birthplace,
        adopter2_citizenship,
        adopter2_phone,
        adopter2_residence,
        adopter2_occupation,
        adopter2_relationship_child,
        adopter2_relationship_adopter1,
        adopter2_relationship_chlds_parent,
        category_of_adopters,
        child_full_name,
        child_dob,
        child_birthplace,
        child_sex,
        received_child_from,
        child_placer_address,
        child_placer_phone,
        adoption_date,
        adoption_type,
        rgstrnt_user
    )
VALUES
    -- Adoption 1
    (
        'John Smith',
        '1980-02-15',
        'M',
        'New York',
        'US',
        '+1234567890',
        'New York',
        'Engineer',
        NULL,
        NULL,
        NULL,
        'Jane Smith',
        '1982-05-20',
        'F',
        'Los Angeles',
        'US',
        '+9876543210',
        'Los Angeles',
        'Doctor',
        NULL,
        NULL,
        NULL,
        'couple',
        'Emily Smith',
        '2010-08-25',
        'Chicago',
        'F',
        'Government agency',
        'Chicago',
        '+1112223334',
        '2023-05-10',
        'domestic',
        1
    ),
    -- Adoption 2
    (
        'Michael Johnson',
        '1975-09-10',
        'M',
        'Houston',
        'US',
        '+4445556667',
        'Houston',
        'Lawyer',
        NULL,
        NULL,
        NULL,
        'Sarah Johnson',
        '1978-12-30',
        'F',
        'Houston',
        'US',
        '+7778889991',
        'Houston',
        'Teacher',
        NULL,
        NULL,
        NULL,
        'couple',
        'Sophia Johnson',
        '2015-03-12',
        'Houston',
        'F',
        'Childcare institution',
        'Houston',
        '+5556667778',
        '2022-10-20',
        'intercountry',
        2
    );

-- Adoption 5
INSERT INTO
    AdoptionRegistrations (
        adopter1_full_name,
        adopter1_dob,
        adopter1_sex,
        adopter1_birthplace,
        adopter1_citizenship,
        adopter1_phone,
        adopter1_residence,
        adopter1_occupation,
        adopter1_relationship_child,
        adopter1_relationship_adopter2,
        adopter1_relationship_chlds_parent,
        adopter2_full_name,
        adopter2_dob,
        adopter2_sex,
        adopter2_birthplace,
        adopter2_citizenship,
        adopter2_phone,
        adopter2_residence,
        adopter2_occupation,
        adopter2_relationship_child,
        adopter2_relationship_adopter1,
        adopter2_relationship_chlds_parent,
        category_of_adopters,
        child_full_name,
        child_dob,
        child_birthplace,
        child_sex,
        received_child_from,
        child_placer_address,
        child_placer_phone,
        adoption_date,
        adoption_type,
        rgstrnt_user
    )
VALUES
    (
        'Maria Hernandez',
        '1976-01-12',
        'F',
        'Madrid',
        'Spain',
        '+34911234567',
        'Madrid',
        'Engineer',
        NULL,
        NULL,
        NULL,
        'Carlos Hernandez',
        '1974-05-29',
        'M',
        'Barcelona',
        'Spain',
        '+34987654321',
        'Barcelona',
        'Teacher',
        NULL,
        NULL,
        NULL,
        'couple',
        'Ana Hernandez',
        '2018-10-15',
        'Seville',
        'F',
        'Orphanage',
        'Seville',
        '+34678901234',
        '2024-02-20',
        'intercountry',
        5
    );

INSERT INTO
    JudicialSeparations (
        petitioner_full_name,
        petitioner_sex,
        petitioner_dob,
        petitioner_birthplace,
        petitioner_citizenship,
        petitioner_phone,
        petitioner_residence,
        respondent_full_name,
        respondent_sex,
        respondent_dob,
        respondent_birthplace,
        respondent_citizenship,
        respondent_phone,
        respondent_residence,
        marriage_date,
        marriage_place,
        separation_reference_path,
        separation_reason,
        separation_date,
        rgstrnt_user
    )
VALUES
    (
        'Rachel Taylor',
        'F',
        '1986-05-20',
        'Westside, USA',
        'USA',
        '777-888-9999',
        '111 Hillcrest Rd, Westside',
        'Mark Johnson',
        'M',
        '1983-09-10',
        'Northtown, USA',
        'USA',
        '333-444-5555',
        '222 Maple Ave, Northtown',
        '2015-02-28',
        'Northtown Hall, Northtown',
        '/path/to/separation/file1.pdf',
        'Domestic violence',
        '2022-12-15',
        3
    ),
    (
        'Patrick Roberts',
        'M',
        '1972-11-18',
        'Downtown, USA',
        'USA',
        '555-666-7777',
        '789 Park Blvd, Downtown',
        'Michelle Adams',
        'F',
        '1975-04-25',
        'Uptown, USA',
        'USA',
        '999-000-1111',
        '456 Lakeview Dr, Uptown',
        '2000-10-10',
        'Uptown Court, Uptown',
        '/path/to/separation/file2.pdf',
        'Financial disputes',
        '2023-01-20',
        4
    ),
    (
        'Jessica Lee',
        'F',
        '1982-08-15',
        'Hometown, USA',
        'USA',
        '222-333-4444',
        '789 Hillside Ave, Hometown',
        'Ryan Wilson',
        'M',
        '1980-03-28',
        'Cityside, USA',
        'USA',
        '888-999-1111',
        '123 Oak St, Cityside',
        '2010-06-12',
        'Cityside Hall, Cityside',
        '/path/to/separation/file3.pdf',
        'Irreconcilable differences',
        '2023-03-10',
        5
    );

INSERT INTO
    AnnulmentRegistrations (
        petitioner_full_name,
        petitioner_dob,
        petitioner_sex,
        petitioner_residence,
        petitioner_citizenship,
        petitioner_phone,
        petitioner_birthplace,
        respondent_full_name,
        respondent_dob,
        respondent_sex,
        respondent_residence,
        respondent_citizenship,
        respondent_phone,
        respondent_birthplace,
        marriage_date,
        marriage_place,
        annulment_reasons,
        annulment_reference_file_path,
        annulment_date,
        rgstrnt_user
    )
VALUES
    (
        'David Thompson',
        '1983-06-18',
        'M',
        '789 Oak St, Springfield',
        'USA',
        '333-444-5555',
        'Springfield, USA',
        'Emma White',
        '1985-09-30',
        'F',
        '567 Maple Ave, Greenvale',
        'USA',
        '666-777-8888',
        'Greenvale, USA',
        '2008-04-15',
        'Greenvale Chapel, Greenvale',
        'Adultery',
        '/path/to/annulment/file1.pdf',
        '2023-08-10',
        3
    ),
    (
        'Sophia Clark',
        '1980-02-12',
        'F',
        '456 Pine Rd, Riverdale',
        'USA',
        '222-111-9999',
        'Riverdale, USA',
        'Jack Wilson',
        '1982-11-05',
        'M',
        '321 Elm Ave, Lakeside',
        'USA',
        '888-999-0000',
        'Lakeside, USA',
        '2011-10-20',
        'St. Mary Cathedral, Riverdale',
        'Misrepresentation of facts',
        '/path/to/annulment/file2.pdf',
        '2023-09-25',
        4
    ),
    (
        'Daniel Brown',
        '1975-08-30',
        'M',
        '987 Cedar Dr, Hilltop',
        'USA',
        '111-222-3333',
        'Hilltop, USA',
        'Olivia Miller',
        '1978-12-03',
        'F',
        '654 Oak St, Seaside',
        'USA',
        '444-555-6666',
        'Seaside, USA',
        '1998-03-05',
        'Seaside Church, Seaside',
        'Lack of consent',
        '/path/to/annulment/file3.pdf',
        '2023-07-05',
        5
    );

INSERT INTO
    JudicialSeparations (
        petitioner_full_name,
        petitioner_sex,
        petitioner_dob,
        petitioner_birthplace,
        petitioner_citizenship,
        petitioner_phone,
        petitioner_residence,
        respondent_full_name,
        respondent_sex,
        respondent_dob,
        respondent_birthplace,
        respondent_citizenship,
        respondent_phone,
        respondent_residence,
        marriage_date,
        marriage_place,
        separation_reference_path,
        separation_reason,
        separation_date,
        rgstrnt_user
    )
VALUES
    (
        'Michael Green',
        'M',
        '1976-02-10',
        'Cityville, USA',
        'USA',
        '111-222-3333',
        '456 Hilltop Rd, Cityville',
        'Sarah White',
        'F',
        '1980-11-15',
        'Villagetown, USA',
        'USA',
        '444-555-6666',
        '789 Valley Dr, Villagetown',
        '2000-09-05',
        'City Hall, Cityville',
        '/path/to/separation/file.pdf',
        'Conflict in family values',
        '2022-10-20',
        1
    ),
    (
        'Emily Young',
        'F',
        '1984-07-20',
        'Harbortown, USA',
        'USA',
        '222-333-4444',
        '567 Beach Blvd, Harbortown',
        'Thomas Brown',
        'M',
        '1980-04-02',
        'Mountainview, USA',
        'USA',
        '999-888-7777',
        '890 Peak Ave, Mountainview',
        '2012-03-15',
        'Harbor Church, Harbortown',
        '/path/to/another/separation/file.pdf',
        'Financial disagreements',
        '2023-01-05',
        2
    );

INSERT INTO
    AnnulmentRegistrations (
        petitioner_full_name,
        petitioner_dob,
        petitioner_sex,
        petitioner_residence,
        petitioner_citizenship,
        petitioner_phone,
        petitioner_birthplace,
        respondent_full_name,
        respondent_dob,
        respondent_sex,
        respondent_residence,
        respondent_citizenship,
        respondent_phone,
        respondent_birthplace,
        marriage_date,
        marriage_place,
        annulment_reasons,
        annulment_reference_file_path,
        annulment_date,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        '1980-05-15',
        'M',
        '123 Main St, Anytown',
        'USA',
        '123-456-7890',
        'Anytown, USA',
        'Jane Smith',
        '1985-09-20',
        'F',
        '456 Oak Ave, Othertown',
        'USA',
        '987-654-3210',
        'Othertown, USA',
        '2005-07-10',
        'Church of St. Mary, Anytown',
        'Fraudulent marriage',
        '/path/to/reference/file.pdf',
        '2023-04-25',
        1
    ),
    (
        'Alice Brown',
        '1982-08-25',
        'F',
        '789 Elm St, New City',
        'USA',
        '555-123-4567',
        'New City, USA',
        'Bob Johnson',
        '1978-03-12',
        'M',
        '321 Pine Rd, Smalltown',
        'USA',
        '777-999-8888',
        'Smalltown, USA',
        '2010-12-01',
        'Chapel of Holy Cross, New City',
        'Irreconcilable differences',
        '/path/to/another/file.pdf',
        '2023-06-15',
        2
    );

INSERT INTO
    DeathRegistrations (
        deceased_full_name,
        deceased_title,
        deceased_sex,
        deceased_age,
        deceased_citizenship,
        death_date,
        death_place,
        death_cause,
        death_evidence_filepath,
        declarant_full_name,
        declarant_sex,
        declarant_phone,
        declarant_residence,
        declarant_relation,
        declarant_relation_other_text,
        rgstrnt_user
    )
VALUES
    (
        'John Doe',
        'Mr',
        'M',
        78,
        'US',
        '2023-05-15',
        'City Hospital',
        'Natural causes',
        '/path/to/evidence/file.pdf',
        'Jane Doe',
        'F',
        '123-456-7890',
        '123 Main St, City',
        'relative',
        NULL,
        1
    ),
    (
        'Mary Smith',
        'Ms',
        'F',
        65,
        'UK',
        '2023-06-20',
        'Home',
        'Heart failure',
        '/path/to/evidence/file.pdf',
        'Michael Smith',
        'M',
        '987-654-3210',
        '456 Elm St, Town',
        'lived_together',
        NULL,
        2
    ),
    (
        'David Johnson',
        'Dr',
        'M',
        45,
        'CA',
        '2023-07-10',
        'Hospital XYZ',
        'Cancer',
        '/path/to/evidence/file.pdf',
        'Sarah Johnson',
        'F',
        '555-123-4567',
        '789 Oak Ave, Village',
        'neighbor',
        NULL,
        3
    ),
    (
        'Emily Brown',
        'Miss',
        'F',
        80,
        'AU',
        '2023-08-05',
        'Nursing Home',
        'Old age',
        '/path/to/evidence/file.pdf',
        'Thomas Brown',
        'M',
        '222-333-4444',
        '101 Pine Rd, County',
        'other',
        'Friend',
        1
    ),
    (
        'Michael Davis',
        'Mr',
        'M',
        55,
        'NZ',
        '2023-09-12',
        'Accident Site',
        'Traffic accident',
        '/path/to/evidence/file.pdf',
        'Jessica Davis',
        'F',
        '777-888-9999',
        '222 Cedar Ln, City',
        'relative',
        NULL,
        2
    );